// <auto-generated />
namespace ParkAr.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class paso3_AlterTableValorCategoria : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(paso3_AlterTableValorCategoria));
        
        string IMigrationMetadata.Id
        {
            get { return "201705160349134_paso3_AlterTableValorCategoria"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
