// <auto-generated />
namespace ParkAr.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class paso2_CargoDatosEnTablas : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(paso2_CargoDatosEnTablas));
        
        string IMigrationMetadata.Id
        {
            get { return "201705160313238_paso2_CargoDatosEnTablas"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
